### PR TITLE
readable-stream@3

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by aduh95** [comment]
If Node.js 4 and 5 support is dropped, we can also remove the  `safe-buffer` dependency.

**Comment by mcollina** [comment]
+1 to remove safe-buffer

**Comment by hugomrdias** [comment]
@mcollina anything i can do to move this along ?

**Comment by rvagg** [comment]
lgtm, I guess this is semver-major, @mcollina do you want to cut a release?

**Comment by mcollina** [comment]
Yes it is!

Il giorno gio 28 feb 2019 alle 06:06 Rod Vagg <notifications@github.com> ha
scritto:

**Pull request merged**
