### PR TITLE
v6.0.0 - BigInt support & readable-stream@4

### PR DESCRIPTION
**Pull request by rvagg**
Closes #109 & #87, incorporates #87 and #113, /cc @yuyaryshev & @piranna

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by piranna** [comment]
Ok, found the issue: it got fixed by adding `export = BufferList;` at the end of file `BufferList.d.ts` :-)

**Comment by piranna** [comment]
> Ok, found the issue: it got fixed by adding `export = BufferList;` at the end of file `BufferList.d.ts` :-)

I tried to do a PR with this change but something odd is happening when running the tests. I'm not a Typescript expert, so maybe I've missed something, but definitely when setting that line in my node_modules, it works.

**Comment by rvagg** [comment]
@alexandercerutti would you mind weighing in here? See @piranna's error output above.

Since it's already out in a minor release and this isn't going to change anything I'm not going to treat TS problems as block this, we can follow-up with a fix.

**Comment by piranna** [comment]
> I'm not going to treat TS problems as block this, we can follow-up with a fix.

Fair enough.

**Comment by alexandercerutti** [comment]
I've chosen to use `interface` due to how ones can interact with `bl`'s API.
At the current situation, bl can be created via `new`, via `function call` or have static methods.

The fact that we have that `function call` forced me to use `interface`. `@types/bl` do not allow this.

I don't know if having `bl/BufferList` as import source is a planned feature. I mean, main is `bl.js` and it (along with `index.d.ts`) contains all that matters for creating a new Bufferlist.

**Comment by rvagg** [comment]
I think that if/when we go to ESM and have an exports map, `"BufferList.js"` (or perhaps just `"BufferList"`) is probably going to be on the list along with the default. That export would have the nice property of not pulling in `readable-stream` where you care about your dependency tree being compact. So we should probably export it from `BufferList.d.ts` so it's resolved properly when you're just consuming `BufferList.js`?

**Comment by rvagg** [comment]
^ my point about ESM is just instructive, today `require('bl/BufferList.js')` has the same effect

**Comment by piranna** [comment]
We can add an `exports` field in the `package.json` file right now, there's no need to wait to use ESM... they are not inter-dependent features.

**Comment by rvagg** [comment]
@piranna yeah but it's not really necessary and may be a breaking change because I think it excludes people using imports with different names? (`require('bl/BufferList.js')` vs `require('bl/BufferList')`, even `require('bl/bl.js')`). I'm just trying to reinforce your point that we probably need to `export` from `BufferList.d.ts` for those that are importing just that module.

**Comment by piranna** [comment]
@rvagg just to be sure, I'm talking about https://nodejs.org/api/packages.html#package-entry-points. Are we talking about the same thing? If you are concerned about importing using extensions, we can add an entry for them too.

Regarding adding default `export` to `BufferList.d.ts`, yes, we need it :-)

**Comment by piranna** [comment]
> I'm just talking about the fact that people want to consume just `BufferList.js` and we should make sure to support that.

Yes! And I'm one of them! :-) What I say is, we can be able to add ALL the files that we want to export, so people (and me! :-D) can still be able to access :-) Something like this:

```json
{
  "exports": {
    ".": "./index.js",
    "./index": "./index.js",
    "./index.js": "./index.js",
    "./BufferList": "./BufferList.js",
    "./BufferList.js": "./BufferList.js",
  }
}
```

A bit bloated to add both extension and extensionless entries, but you get the idea, and the same for the types.

If this is not what you are talking about please clarify, because I don't get your point... :-/

**Comment by rvagg** [comment]
uhh, yeah we've diverged a long way from the original point, so let's drop this, you're correct but it's not really relevant; we're dealing with this from @alexandercerutti:

> I don't know if having bl/BufferList as import source is a planned feature. I mean, main is bl.js and it (along with index.d.ts) contains all that matters for creating a new Bufferlist.

the answer being - yes, it's a planned feature, it's in wide usage, so we should allow for it and I _think_ that means we need an `export` from BufferList.d.ts but I'm also not exactly an expert in handling typedefs.

**Comment by alexandercerutti** [comment]
@rvagg I guess the way to achieve this is as @piranna said and as I set on the bottom of `index.d.ts`:

https://github.com/rvagg/bl/blob/a59710d5abddf33e7ed71963b9071d53926156aa/index.d.ts#L88

So, when importing `bl`, `export` will expose what comes from `bl.js`.
When importing `bl/BufferList(.js)`, `export` will expose what has been declared.

More infos about `export =` available [here](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require).

**Comment by piranna** [comment]
> I guess the way to achieve this is as @piranna said

Yes, I copied the idea from `index.d.ts` file, and it works on node_modules, but for some reason `npm test` fails when applying the changes in the code.

**Comment by alexandercerutti** [comment]
I'll check it later @piranna. @rvagg what about moving this discussion to a discussion topic or another issue? I'm losing notifications as this is already been merged :D

**Comment by piranna** [comment]
> what about moving this discussion to a discussion topic or another issue? I'm losing notifications as this is already been merged :D

Never used discussions, but I think it's ok for me. Regarding notifications, I still get them in my mail...

**Comment by piranna** [comment]
And thank you for taking a look on this :-)

**Comment by alexandercerutti** [comment]
@piranna @rvagg I've tried to add that line, but it seems to conflict with other exports. I'm actually a bit stuck there because `index.d.ts` uses `Bufferlist.d.ts` things and I don't know how to export both types and things with `export =`. I have to experiment a little bit more. If you understand a way to do so, let me know!

**Comment by alexandercerutti** [comment]
I might have found a solution to the problem! Sadly, today I didn't have any time to detail it.
Tomorrow I'll open a new issue to discuss this. If you want to open it, be my guest!

**Comment by piranna** [comment]
I'm honestly interested on knowing about your solution :-)

**Pull request merged**
