### PR TITLE
added support for readUIntLE / readUIntBE / readIntLE / readIntBE

### PR DESCRIPTION
**Pull request by ctusch**
Implements #54.

### CODE REVIEW

**Comment by mcollina** [comment]
@ctusch can you implement suggestion 1?

**Comment by rvagg** [comment]
I think I'm comfortable with 2, we're a long way from 0.10

**Comment by mcollina** [comment]
Then let's do it! :). What should we support @rvagg? 4+? 6+?

**Comment by mcollina** [comment]
I’ll get this out today! +1

**Pull request merged**
